# Generated by Django 4.2.3 on 2023-07-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='acounts.tags'),
        ),
    ]
