# Generated by Django 4.2.4 on 2023-08-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0005_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
